apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-server
spec:
  selector:
    matchLabels:
      app: cal-server
  template:
    metadata:
      labels:
        app: cal-server
    spec:
      containers:
        - name: cal-server
          image: http://192.168.1.148:5000/cheleb/cal-server:0.1.2-SNAPSHOT
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
