apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencies
spec:
  selector:
    matchLabels:
      app: currencies
  template:
    metadata:
      labels:
        app: currencies
    spec:
      containers:
        - name: currencies
          image: localhost:5000/cheleb/currency-service:0.1.17
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp
              containerPort: 5432
          env:
            - name: DB_HOST
              value: postgresql-svc
            - name: POSTGRES_USERNAME
              value: test
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secrets
                  key: POSTGRES_PASSWORD
