apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencies
spec:
  selector:
    matchLabels:
      app: currencies
  template:
    metadata:
      labels:
        app: currencies
    spec:
      containers:
        - name: currencies
          image: currency-service:0.1.0-SNAPSHOT
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 5432
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: test
            - name: DB_PASSWORD
              value: test

