apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zio-hexagonal-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/cheleb/zio-hexagonal-app-config.git
    targetRevision: HEAD
    path: modules
  destination: 
    server: https://kubernetes.default.svc
    namespace: zio-hexa

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true