apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zio-hexagonal-apps
  annotations:
    argocd-image-updater.argoproj.io/image-list: cal=cheleb/cal-server,currency=cheleb/currency-service
    argocd-image-updater.argoproj.io/cal.update-strategy: latest
    argocd-image-updater.argoproj.io/currency.update-strategy: latest

  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/cheleb/zio-hexagonal-app-config.git
    targetRevision: HEAD
    path: modules
  destination:
    server: https://kubernetes.default.svc
    namespace: ziohexa

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
