---
apiVersion: v1
kind: Namespace
metadata:
  name: ziohexa
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: zio-hexagonal-app
  namespace: argocd
# finalizers:
#   - resources-finalizer.argocd.argoproj.io
spec:
  description: ZIO Hexagonal App
  sourceRepos:
    -
  destinations:
    - namespace: ziohexa
      server: https://kubernetes.default.svc
